name: Trivy Image Scan (example)
on: [push, pull_request]
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Option A: scan a public image (no Docker build required)
      - name: Run Trivy on nginx:latest
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'nginx:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
